x-logging:
  &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'

version: "3.7"
services:
  api:
    restart: always
    build: .
    ports:
      - "80:80"
      - "443:443"

# .\gradlew build ; docker-compose up -d --build
